[package]
name = "luccas"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm4 = { version = "0.2.0", features = ["std", "include-sprites"] }

[profile.release]
opt-level = "z"
lto = true