[package]
name = "luccas"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
buddy-alloc = "0.5.1"
wasm4 = { version = "0.2.0", features = ["std"] }

[profile.release]
opt-level = "z"
lto = true
